---
# l2-demo/servers/tasks/main.yml
- name: Disable AAAA DNS lookups
  replace:
    dest=/etc/gai.conf
    regexp="#precedence ::ffff:0:0/96  10"
    replace="precedence ::ffff:0:0/96  100"

- name: Add Debian Apt Sources
  apt_repository:
    repo='deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free'

- name: Install FPing
  apt: name=fping update_cache=yes

- name: install ifenslave
  apt: name=ifenslave state=present

- name: install vlan
  apt: name=vlan state=present

- name: adding bonding and rtc modules to /etc/modules
  lineinfile: dest=/etc/modules line="{{ item }}"
  with_items: 
     - "rtc"
     - "bonding" 
     - "8021q"

- name: push /etc/network/configuration for servers
  template: src=host_interfaces.j2 dest=/etc/network/interfaces

- name: ifup all interfaces
  command: "/sbin/ifup -a"

- name: reboot
  command: "/sbin/reboot"
