---
- name: Disable AAAA DNS lookups
  replace:
    dest=/etc/gai.conf
    regexp="#precedence ::ffff:0:0/96  10"
    replace="precedence ::ffff:0:0/96  100"

- name: Add Debian Apt Sources
  apt_repository:
    repo='deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free'

- name: Copy Quagga daemons file
  copy: src=daemons dest=/etc/quagga/daemons backup=yes
  notify: restart quagga

- name: Enable Quagga Reload
  copy: src=quagga dest=/etc/default/quagga
  notify: restart quagga

- name: Force quagga changes
  meta: flush_handlers
